### PR TITLE
M0127CC-591 Add Tutorial Build from CLI with Jenkins and Artifactory

### PR DESCRIPTION
**Pull request by thomasponsmicroej**

### CODE REVIEW

**Comment by frivieremicroej** [comment]
Use guilabel intead of bold

**Comment by frivieremicroej** [comment]
Add section from EABC (anonymous) 
https://gitlab.cross/Infra/I0048_EasyAnt-Build-Component/blob/develop/README.md#use-artifactory-cross-in-eclipse => Add a custom certificate

**Comment by frivieremicroej** [comment]
The doc link is here: https://docs.microej.com/en/feature-m0127cc-591_tutorial_cli/

**Comment by frivieremicroej** [comment]
TODO friviere: 
Add on which version this tuto has been tested: 
- Artifactory: 6.20.1
- Jenkins:

**Comment by frivieremicroej** [comment]
TODO friviere: derivate the general schematics https://docs.microej.com/en/latest/_images/mmm_flow.png with server instances (Jenkins/Artifactory)

**Comment by frivieremicroej** [comment]
Rename env variable EASYANT_HOME => MMM_HOME

**Comment by frivieremicroej** [comment]
remove useless conf lines that are related to customer process
- timestamp 
- delete workspace after build
- In Build triggers tab: Check Poll SCM

**Comment by frivieremicroej** [comment]
TODO friviere: pull up Extract Build Kit section to MMM

**Comment by frivieremicroej** [comment]
Remove Easyant as much as possible

**Comment by frivieremicroej** [comment]
review rename repository names: microej-easyant-release-local & microej-libs-release-local

**Comment by frivieremicroej** [comment]
Add more screenshots after a set of config steps

**Review by frivieremicroej — COMMENTED** [review]
Check if it is still necessary to setup the environment variable MICROEJ_BUIILD_TOOLS in Jenkins as it has already been declared as OS environment variable before

**Comment by frivieremicroej** [comment]
@fpinel-microej please run ASAP this tutorial and monitor the total time spent to get the hello world built
Thanks

**Comment by fpinel-microej** [comment]
Tutorial completed in about 2hours 5minutes, no problem in particular to complete it and was pretty clear start to end.
A small thing that puzzled me though : The `Set Test report XMLs to **/target~/test/xml/**/test-report.xml, **/target~/test/xml/**/*Test.xml` step in Appendix > Customize Jenkins gives me a `'**/target~/test/xml/**/test-report.xml' ne correspond à rien : '**' existe mais pas '**/target~/test/xml/**/test-report.xml'` error. Is this expected/intended ?

**Pull request merged**
